### ISSUE TITLE
`tfjs-node` issue on Windows PC

### ISSUE THREAD

**Issue by naotokui** [naotokui/RhythmVAE_M4L#1]
When I load it on Ableton Live and start training on Windows PC, I got the following error on Max Console `Error: Cannot find module '.../node_modules/@tensorflow/tfjs-node/lib/napi-v4/tfjs_binding.node`

You need to export the device on Windows PC at first.

**Comment by mcwebdev** [comment]
path is wrong, should only have  `../`

**Comment by mcwebdev** [comment]
were you able to sort out the windows path issue? Did you need to create some symbolic links or set path in %environments% etc,, curious.

**Comment by naotokui** [comment]
not yet solved.   thanks for asking.

The actual error message is the following:

> node: details Cannot find module 'C:\Users\naoto\OneDrive\Documents\GitHub\RhythmVAE_M4L\node_modules\@tensorflow\tfjs-node\lib\napi-v3\tfjs_binding.node'
node: stack Error: Cannot find module 'C:\Users\naoto\OneDrive\Documents\GitHub\RhythmVAE_M4L\node_modules\@tensorflow\tfjs-node\lib\napi-v3\tfjs_binding.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Object.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module._load (C:\Program Files\Cycling '74\Max 8\resources\packages\Node For Max\source\lib\nsRunner.js:67:24)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\naoto\OneDrive\Documents\GitHub\RhythmVAE_M4L\node_modules\@tensorflow\tfjs-node\dist\index.js:46:16)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)

I have tried several things:

1. When I just do "script npm install", I got no "lib" directory under "tfjs-node" directory. 

2.  "npm install @tensorflow/tfjs-node --unsafe-perm=true --allow-root" (as suggested [here](https://stackoverflow.com/questions/57537386/cannot-import-tensorflow-tfjs-node-in-nodejs)) gave me the "lib" folder, but under the folder, I got only "tensorflow.dll" and no "tfjs_binding.node".

3.  I tried "npm install @tensorflow/tfjs-node" on Windows terminal, it generated "lib/napi-**v5**/tfjs_binding.node" instead of "lib/napi-**v3**/tfjs_binding.node" and Node for Max seems just ignoring napi-v5 files.

**Comment by mcwebdev** [comment]
On Windows it should simply be  `npm i tfjs --save`. The `@` decorators are only used inside the imports and package json because the package directories are prefixed with `@`.  A pattern some folks are using to appear at the top of a long list of node dependencies.

**Comment by mcwebdev** [comment]
also tfjs is not installed globally, the above cmd must be run in your project directory. the `--save` flag will it add it to your package.json

**Comment by mxkrn** [comment]
So the root of this issue has to do with an outdated version of Node.js. Lucky for us, updating to Max 8.1.2 solves this issue as it is shipped with a newer version of Node.js (12.14.1)! 

Most likely you will still get a `Cannot find module... @tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node` error but because this is the up-to-date N-API version this can be fixed by sending a `script npm install` to the script object.

**Comment by naotokui** [comment]
@mxkrn Thanks for the comment! I tried on Max 8.1.2, but the result was the same. I got the same ` Cannot find module... @tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node` error, even after `script npm install`.  any ideas?

**Comment by naotokui** [comment]
I figured it out!!! Thanks for your help! @mxkrn @mcwebdev

**Comment by vigliensoni** [comment]
@naotokui So what is the fix you found? 

Depending if I'm using Rhythm-VAE on MaxMSP or if I am exporting the M4L device, I have to manually change `napi-v3` to `napi-v5`.
