### ISSUE TITLE
Not playing any MIDI after training

### ISSUE THREAD

**Issue by edivadiranatnom** [naotokui/RhythmVAE_M4L#2]
After training the VAE on 20 midi files, I can see all the possible patterns generated by the model and navigate through the latent vector, but the device isn't producing any MIDI output when I press play. Any suggestion?

**Comment by edivadiranatnom** [comment]
Now I'm getting this error when trying to load midi files in RhythmVAE v0.66

<img width="950" alt="Screenshot 2020-01-01 at 22 36 46" src="https://user-images.githubusercontent.com/18500333/71646345-55fe0600-2ce7-11ea-9fec-6ea5fa9d11ee.png">

**Comment by mcwebdev** [comment]
object is losing scope somewhere in the traversal. Set up some breakpoints and inspect it.

**Comment by naotokui** [comment]
@davidmantegna  so you didn't have this issue in the previous versions, did you? 
Could you try the latest version v0.67?  https://github.com/naotokui/RhythmVAE_M4L/releases/tag/v0.67

**Comment by edivadiranatnom** [comment]
With this version I can upload the midi files, train the model and see the patterns generated, but when I start playing the transport the track doesn't produce any MIDI output...

**Comment by naotokui** [comment]
![image](https://user-images.githubusercontent.com/970319/72038691-a4159980-32e5-11ea-96ff-992167b5dfad.png)

Please make sure you have enabled the sequencer. It's enabled by default.

**Comment by edivadiranatnom** [comment]
Yep it's enabled by default when I load RhythmVAE. 
I tried enabling/disabling it and playing but it still doesn't work :(

**Comment by naotokui** [comment]
Which version of Ableton Live do you use?  Which plugin do you insert after RhythmVAE?

**Comment by edivadiranatnom** [comment]
Ableton 10.1 and a Drum Rack with some percs loaded

**Comment by naotokui** [comment]
that's strange... how about previous versions? did they work?

**Comment by edivadiranatnom** [comment]
I tried all of them because your device has huge potential, but none of them works. 
Some don't let me load the samples, others don't produce any midi output. 
Please fix it 🙏🏻🙏🏻🙏🏻 I'm super interested in this plugin 🤓

**Comment by naotokui** [comment]
I'll do my best!  Do you use the internal Max runtime, or have you set an external Max runtime path? 

More than 10 friends of mine have been using this plugin, but none of them reported this issue....

**Comment by edivadiranatnom** [comment]
Just kept the default settings when installed Max, maybe I'm doing something wrong?

**Comment by naotokui** [comment]
can you capture your screen while testing the device?

**Comment by davidmantegna** [comment]
Here's a short screen recording with v0.70...still not working 😭

[Uploading screenrec.zip…]()

**Comment by edivadiranatnom** [comment]
Here's a screen recording with v0.70...still not working 😭

https://we.tl/t-iAKMBuDbs1

**Comment by naotokui** [comment]
I downloaded the zip file, but I cannot unzip it...    is this really a zip file?

**Comment by naotokui** [comment]
why don't you just upload it to YouTube or somewhere?

**Comment by edivadiranatnom** [comment]
It's a .7z inside. You need to uncompress it another time to get the video

**Comment by edivadiranatnom** [comment]
Just uploaded on Vimeo
https://vimeo.com/384418764

**Comment by naotokui** [comment]
ah ok. I got it!   Can you click "open" button next to Console and copy the contents of your Max console?

**Comment by naotokui** [comment]
It seems something wrong with your MIDI file.  the loss value stayed at 0, which is unusual.   Can you try with these MIDI files again just in case. 
[House.zip](https://github.com/naotokui/RhythmVAE_M4L/files/4051862/House.zip)

**Comment by edivadiranatnom** [comment]
After training with your samples this is the response (the device isn't producing any midi ouput as before)

<img width="1064" alt="Screenshot 2020-01-13 at 02 22 56" src="https://user-images.githubusercontent.com/18500333/72229012-c7716a80-35ab-11ea-9696-78b499047ae2.png">

<img width="1064" alt="Screenshot 2020-01-13 at 02 23 08" src="https://user-images.githubusercontent.com/18500333/72229022-d6581d00-35ab-11ea-8f97-f5c5838a951a.png">

<img width="1064" alt="Screenshot 2020-01-13 at 02 23 15" src="https://user-images.githubusercontent.com/18500333/72229025-dbb56780-35ab-11ea-9859-879dcfeec1da.png">

**Comment by naotokui** [comment]
I found "count_for_me can't load", "shuffle_metro can't load" lines.  These objects are essential for the MIDI generation. something wrong with internal file path settings. I'll check these issues and get back to you as soon as possible.

**Comment by edivadiranatnom** [comment]
Thank you so much, keep me updated :)

**Comment by naotokui** [comment]
One more: did you export the device from the Max project by yourself? or used the one released as a zip file?

**Comment by edivadiranatnom** [comment]
At first I cloned the repo and used the devices in the release folder, then in the following attempts I downloaded the zip files

**Comment by naotokui** [comment]
OK. You use Ableton Live Suite 10.1.6, right?

**Comment by edivadiranatnom** [comment]
it's just v10.1, I skipped 10.1.x updates

**Comment by naotokui** [comment]
maybe that's why! Can you try 10.1.2 or later? The internal Max version was updated in Live 10.1.2 from Max 8.0 to Max 8.1, and the device requires Max 8.1 or later I believe.

**Comment by edivadiranatnom** [comment]
You were right, I updated to 10.1.5 and now everything works! 
Thank you so much for your help 🙌🏻

**Comment by naotokui** [comment]
Great! I should have mentioned that in README. Thanks for opening the issue. Let me know if you come up with something interesting using this device ;-)
