### ISSUE TITLE
Make onset velocity greater than zero.

### ISSUE THREAD

**Issue by vigliensoni** [naotokui/RhythmVAE_M4L#5]
During generation, sometimes there are discrepancies between the onsets that come through `matrix_output` and the velocities carried by `seq_output`.

This behavior makes the user to see a specific pattern in the `live.step` object but there is no sound for some onsets, as can be heard in the attached video:

[![Onsets](https://user-images.githubusercontent.com/492229/77437090-9f2b9680-6dba-11ea-800a-d0839795b8d8.gif)](https://drive.google.com/file/d/10tB5KWTn76V48zTJDwQkaswjhMwsS2ja/view?usp=sharing)

The snare drum in position 47 has a clear onset, but we can't hear it. Checking the output of the `rhythmvae.js` object, we see:

```
matrix_output 25 2 1
matrix_output 47 2 1
...
seq_output: 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
             74 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
...
```
If there is an onset, the second to last velocity shouldn't be zero. 

Checking your code, I realized the scaling of the velocities shouldn't be from 0 to 127 but from 1 to 127. I think this is true since you already checked if there was an onset (so the velocity should be greater than zero). 

https://github.com/naotokui/RhythmVAE_M4L/blob/b450bf6b409b190f00b8488091266ef553e9c767/rhythmvae.js#L206-L211

All in all, my change I propose is in line 210:
``` javascript
sequence.push(Math.floor(velocities[i][j]*127. + 1))

```

I can make a pull request, if you want.

**Comment by naotokui** [comment]
ah, thank you very much for pointing out! I'll fix it!
