### ISSUE TITLE
Reset Position Transport Control in Max4Live

### ISSUE THREAD

**Issue by bakaj** [naotokui/RhythmVAE_M4L#9]
On start and stop in Ableton, the sequencer doesn't reset to its start position. This was an easy fix. Its not the cleanest, but maybe you want to change this for the M4L version.

![Screenshot 2021-01-24 at 12 16 24](https://user-images.githubusercontent.com/15163668/105628629-472c4900-5e3e-11eb-95f7-61f8871c9fd1.png)

**Comment by naotokui** [comment]
Oh, thanks!!! I was not sure how to implement this behavior! much appreciated!
